name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: build protoc
        uses: docker/build-push-action@v2.5.0
        with:
          file: protoc/Dockerfile
          push: true
          tags: hnlq715/protoc:latest
          github-token: ${{ github.token }}
